# Generated by Django 5.1.15 on 2026-05-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('rationale', models.TextField(blank=True)),
                ('n_roles', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('avg_demand', models.FloatField(default=0)),
                ('avg_automation_resistance', models.FloatField(default=0)),
                ('avg_skill_depth', models.FloatField(default=0)),
                ('avg_strategic_importance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['-avg_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TierSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20, unique=True)),
                ('n_roles', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('avg_demand', models.FloatField(default=0)),
                ('avg_automation_resistance', models.FloatField(default=0)),
                ('avg_skill_depth', models.FloatField(default=0)),
                ('avg_strategic_importance', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-avg_score'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('demand', models.PositiveSmallIntegerField()),
                ('automation_resistance', models.PositiveSmallIntegerField()),
                ('skill_depth', models.PositiveSmallIntegerField()),
                ('strategic_importance', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField(db_index=True)),
                ('tier', models.CharField(choices=[('fortress', 'Fortress'), ('safe', 'Safe'), ('stable', 'Stable'), ('exposed', 'Exposed'), ('at_risk', 'At risk')], db_index=True, max_length=20)),
                ('demand_trend', models.CharField(choices=[('rising', 'Rising'), ('flat', 'Flat'), ('declining', 'Declining')], db_index=True, max_length=20)),
                ('salary_low_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_high_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='roles.category')),
            ],
            options={
                'ordering': ['-score', 'role'],
            },
        ),
        migrations.CreateModel(
            name='RoleMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postings_2024_baseline', models.PositiveIntegerField(blank=True, null=True)),
                ('postings_2025_jan', models.PositiveIntegerField(blank=True, null=True)),
                ('postings_2026_current', models.PositiveIntegerField(blank=True, null=True)),
                ('postings_yoy_pct', models.FloatField(blank=True, null=True)),
                ('postings_2yr_pct', models.FloatField(blank=True, null=True)),
                ('ai_mention_pct_2026', models.FloatField(blank=True, null=True)),
                ('ai_mention_delta_pp', models.FloatField(blank=True, null=True)),
                ('copilot_mention_pct_2026', models.FloatField(blank=True, null=True)),
                ('trend_direction', models.CharField(blank=True, max_length=40)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='roles.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('role', 'category'), name='unique_role_per_category'),
        ),
    ]
