# Generated by Django 5.2.17 on 2026-08-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_role_ai_augmentation_potential_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
